---
os: linux
dist: jammy
language: python
python:
  - '3.10'
before_install:
  - pip install --upgrade pip setuptools
branches:
  only:
    - main
jobs:
  include:
    - name: Check YAML format
      install:
        - pip install tox
      script:
        - tox -e yamllint
    - name: Check Markdown Format
      install:
        - pip install tox
      script:
        - tox -e pymarkdown
    - name: Check Gherkin format
      language: node_js
      node_js: 22
      before_install: skip
      install:
        - npm install gherkin-lint
      script:
        - npx gherkin-lint
    - name: Check Python Format
      install:
        - pip install tox
      script:
        - tox -e flake8
    - name: Check Bash format
      install:
        - pip install tox
      script:
        - tox -e shellcheck
    - name: Test
      install:
        - pip install tox
      script:
        - tox -e test
    - name: Behave
      service:
        - docker
      addons:
        # For the `SONARQUBE_SCANNER_PARAMS` variable
        sonarcloud:
          token: ${SONAR_TOKEN}
      install:
        - pip install tox
      script:
        - tox -e behave
        - tox -e coverage-report
        - >
          docker run --rm
          -e SONARQUBE_SCANNER_PARAMS
          -e SONAR_TOKEN="${SONAR_TOKEN}"
          -v "`pwd`:/usr/src"
          sonarsource/sonar-scanner-cli
